=== Sendoaa/Web_DAW_1/xm_xs/calendar.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="temporada">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="numtemp"/>
        <xs:element name="jornada" maxOccurs="unbounded" minOccurs="0">
          <xs:annotation>
            <xs:documentation> Datos de las jornadas  Jornada 6  Jornada 7  Jornada 8  Jornada 9  Jornada 10 </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="partido" maxOccurs="unbounded" minOccurs="0">
                <xs:annotation>
                  <xs:documentation> Eliminamos el cuarto partido extra </xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="fecha"/>
                    <xs:element type="xs:string" name="hora" maxOccurs="unbounded" minOccurs="0"/>
                    <xs:element name="equipos">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="local"/>
                          <xs:element type="xs:string" name="puntoslocal"/>
                          <xs:element type="xs:string" name="visitante"/>
                          <xs:element type="xs:string" name="puntosvisitante"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:integer" name="num" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Sendoaa/Web_DAW_1/xm_xs/2021.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="calendar.xsl"?>
<temporada xsi:noNamespaceSchemaLocation="calendar.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <numtemp>Temporada 2021</numtemp>
     <!-- Datos de las jornadas -->
    <jornada num="1">
        <partido>
            <fecha>Viernes, 13 de octubre</fecha>
            <hora>20:00</hora>
            <equipos>
                <local>Rams</local>
                   <puntoslocal>55</puntoslocal>
                   <visitante>Bengals</visitante>
                   <puntosvisitante>25</puntosvisitante>
               </equipos>
        </partido>
        <partido>
            <fecha>Sábado, 14 de octubre</fecha>
            <hora>21:30</hora>
            <equipos>
                <local>Cardinals</local>
                <puntoslocal>45</puntoslocal>
                <visitante>Raiders</visitante>
                <puntosvisitante>35</puntosvisitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Domingo, 15 de octubre</fecha>
            <hora>23:00</hora>
            <equipos>
                <local>Cowboys</local>
                <puntoslocal>15</puntoslocal>
                <visitante>Steelers</visitante>
                <puntosvisitante>45</puntosvisitante>
            </equipos>
        </partido>
    </jornada>
    <jornada num="2">
        <partido>
            <fecha>Viernes, 20 de octubre</fecha>
            <hora>19:00</hora>
            <equipos>
                <local>Bengals</local>
                <puntoslocal>35</puntoslocal>
                <visitante>Rams</visitante>
                <puntosvisitante>20</puntosvisitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Sábado, 21 de octubre</fecha>
            <hora>21:00</hora>
            <equipos>
                <local>Raiders</local>
                <puntoslocal>25</puntoslocal>
                <visitante>Cardinals</visitante>
                <puntosvisitante>30</puntosvisitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Domingo, 22 de octubre</fecha>
            <hora>18:00</hora>
            <equipos>
                <local>Steelers</local>
                <puntoslocal>35</puntoslocal>
                <visitante>Cowboys</visitante>
                <puntosvisitante>40</puntosvisitante>
            </equipos>
        </partido>
    </jornada>
    <jornada num="3">
        <partido>
            <fecha>Martes, 24 de octubre</fecha>
            <hora>16:30</hora>
            <equipos>
                <local>Cardinals</local>
                <puntoslocal>20</puntoslocal>
                <visitante>Raiders</visitante>
                <puntosvisitante>25</puntosvisitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Miércoles, 25 de octubre</fecha>
            <hora>18:00</hora>
            <equipos>
                <local>Cowboys</local>
                <puntoslocal>30</puntoslocal>
                <visitante>Bengals</visitante>
                <puntosvisitante>35</puntosvisitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Jueves, 26 de octubre</fecha>
            <hora>20:00</hora>
            <equipos>
                <local>Rams</local>
                <puntoslocal>40</puntoslocal>
                <visitante>Steelers</visitante>
                <puntosvisitante>15</puntosvisitante>
            </equipos>
        </partido>
    </jornada>
    
    <jornada num="4">
        <!-- Eliminamos el cuarto partido extra -->
        <partido>
            <fecha>Martes, 7 de noviembre</fecha>
            <hora>17:15</hora>
            <equipos>
                <local>Raiders</local>
                <puntoslocal>25</puntoslocal>
                <visitante>Cardinals</visitante>
                <puntosvisitante>30</puntosvisitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Miércoles, 8 de noviembre</fecha>
            <hora>18:45</hora>
            <equipos>
                <local>Bengals</local>
                <puntoslocal>35</puntoslocal>
                <visitante>Cowboys</visitante>
                <puntosvisitante>40</puntosvisitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Jueves, 9 de noviembre</fecha>
            <hora>20:30</hora>
            <equipos>
                <local>Steelers</local>
                <puntoslocal>25</puntoslocal>
                <visitante>Rams</visitante>
                <puntosvisitante>30</puntosvisitante>
            </equipos>
        </partido>
    </jornada>
    <jornada num="5">
        <partido>
            <fecha>Lunes, 20 de noviembre</fecha>
            <hora>16:45</hora>
            <equipos>
                <local>Rams</local>
                <puntoslocal>35</puntoslocal>
                <visitante>Steelers</visitante>
                <puntosvisitante>40</puntosvisitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Martes, 21 de noviembre</fecha>
            <hora>18:15</hora>
            <equipos>
                <local>Bengals</local>
                <puntoslocal>25</puntoslocal>
                <visitante>Cardinals</visitante>
                <puntosvisitante>30</puntosvisitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Jueves, 23 de noviembre</fecha>
            <hora>21:15</hora>
            <equipos>
                <local>Cowboys</local>
                <puntoslocal>25</puntoslocal>
                <visitante>Raiders</visitante>
                <puntosvisitante>30</puntosvisitante>
            </equipos>
        </partido>
    </jornada>    
   <!-- Jornada 6 -->
    <jornada num="6">
        <partido>
            <fecha>Lunes, 4 de diciembre</fecha>
            <hora>16:45</hora>
            <equipos>
                <local>Steelers</local>
                <puntoslocal>15</puntoslocal>
                <visitante>Rams</visitante>
                <puntosvisitante>20</puntosvisitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Martes, 5 de diciembre</fecha>
            <hora>18:15</hora>
            <equipos>
                <local>Cardinals</local>
                <puntoslocal>25</puntoslocal>
                <visitante>Bengals</visitante>
                <puntosvisitante>30</puntosvisitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Jueves, 7 de diciembre</fecha>
            <hora>21:15</hora>
            <equipos>
                <local>Raiders</local>
                <puntoslocal>20</puntoslocal>
                <visitante>Cowboys</visitante>
                <puntosvisitante>25</puntosvisitante>
            </equipos>
        </partido>
    </jornada>

    <!-- Jornada 7 -->
    <jornada num="7">
        <partido>
            <fecha>Lunes, 11 de diciembre</fecha>
            <hora>16:30</hora>
            <equipos>
                <local>Cowboys</local>
                <puntoslocal>30</puntoslocal>
                <visitante>Rams</visitante>
                <puntosvisitante>35</puntosvisitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Martes, 12 de diciembre</fecha>
            <hora>18:00</hora>
            <equipos>
                <local>Raiders</local>
                <puntoslocal>25</puntoslocal>
                <visitante>Cardinals</visitante>
                <puntosvisitante>25</puntosvisitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Miércoles, 13 de diciembre</fecha>
            <hora>19:30</hora>
            <equipos>
                <local>Bengals</local>
                <puntoslocal>35</puntoslocal>
                <visitante>Steelers</visitante>
                <puntosvisitante>40</puntosvisitante>
            </equipos>
        </partido>
    </jornada>
    <!-- Jornada 8 -->
    <jornada num="8">
        <partido>
            <fecha>Lunes, 18 de diciembre</fecha>
            <hora>16:30</hora>
            <equipos>
                <local>Rams</local>
                <puntoslocal>25</puntoslocal>
                <visitante>Cowboys</visitante>
                <puntosvisitante>30</puntosvisitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Martes, 19 de diciembre</fecha>
            <hora>18:00</hora>
            <equipos>
                <local>Bengals</local>
                <puntoslocal>35</puntoslocal>
                <visitante>Raiders</visitante>
                <puntosvisitante>40</puntosvisitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Miércoles, 20 de diciembre</fecha>
            <hora>19:30</hora>
            <equipos>
                <local>Cardinals</local>
                <puntoslocal>20</puntoslocal>
                <visitante>Steelers</visitante>
                <puntosvisitante>25</puntosvisitante>
            </equipos>
        </partido>
    </jornada>

    <!-- Jornada 9 -->
    <jornada num="9">
        <partido>
            <fecha>Lunes, 20 de diciembre</fecha>
            <hora>16:30</hora>
            <equipos>
                <local>Cardinals</local>
                <puntoslocal>15</puntoslocal>
                <visitante>Bengals</visitante>
                <puntosvisitante>20</puntosvisitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Martes, 21 de diciembre</fecha>
            <hora>18:00</hora>
            <equipos>
                <local>Steelers</local>
                <puntoslocal>25</puntoslocal>
