=== Sendoaa/Web_DAW_1/xml/xsd/clasificacion.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="tabla">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tempActual" type="xs:int" />
                <xs:element name="club">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="equipo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="enlace" type="xs:string" />
                                        <xs:element name="imagen" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="puntuacion">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="G" type="xs:int" />
                                        <xs:element name="E" type="xs:int" />
                                        <xs:element name="P" type="xs:int" />
                                        <xs:element name="J" type="xs:int" />
                                        <xs:element name="PF" type="xs:int" />
                                        <xs:element name="PC" type="xs:int" />
                                        <xs:element name="PT" type="xs:int" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="club">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="equipo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="enlace" type="xs:string" />
                                        <xs:element name="imagen" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="puntuacion">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="G" type="xs:int" />
                                        <xs:element name="E" type="xs:int" />
                                        <xs:element name="P" type="xs:int" />
                                        <xs:element name="J" type="xs:int" />
                                        <xs:element name="PF" type="xs:int" />
                                        <xs:element name="PC" type="xs:int" />
                                        <xs:element name="PT" type="xs:int" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="club">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="equipo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="enlace" type="xs:string" />
                                        <xs:element name="imagen" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="puntuacion">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="G" type="xs:int" />
                                        <xs:element name="E" type="xs:int" />
                                        <xs:element name="P" type="xs:int" />
                                        <xs:element name="J" type="xs:int" />
                                        <xs:element name="PF" type="xs:int" />
                                        <xs:element name="PC" type="xs:int" />
                                        <xs:element name="PT" type="xs:int" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="club">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="equipo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="enlace" type="xs:string" />
                                        <xs:element name="imagen" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="puntuacion">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="G" type="xs:int" />
                                        <xs:element name="E" type="xs:int" />
                                        <xs:element name="P" type="xs:int" />
                                        <xs:element name="J" type="xs:int" />
                                        <xs:element name="PF" type="xs:int" />
                                        <xs:element name="PC" type="xs:int" />
                                        <xs:element name="PT" type="xs:int" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="club">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="equipo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="enlace" type="xs:string" />
                                        <xs:element name="imagen" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="puntuacion">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="G" type="xs:int" />
                                        <xs:element name="E" type="xs:int" />
                                        <xs:element name="P" type="xs:int" />
                                        <xs:element name="J" type="xs:int" />
                                        <xs:element name="PF" type="xs:int" />
                                        <xs:element name="PC" type="xs:int" />
                                        <xs:element name="PT" type="xs:int" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="club">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="equipo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="enlace" type="xs:string" />
                                        <xs:element name="imagen" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="puntuacion">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="G" type="xs:int" />
                                        <xs:element name="E" type="xs:int" />
                                        <xs:element name="P" type="xs:int" />
                                        <xs:element name="J" type="xs:int" />
                                        <xs:element name="PF" type="xs:int" />
                                        <xs:element name="PC" type="xs:int" />
                                        <xs:element name="PT" type="xs:int" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="club">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="equipo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="enlace" type="xs:string" />
                                        <xs:element name="imagen" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="puntuacion">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="G" type="xs:int" />
                                        <xs:element name="E" type="xs:int" />
                                        <xs:element name="P" type="xs:int" />
                                        <xs:element name="J" type="xs:int" />
                                        <xs:element name="PF" type="xs:int" />
                                        <xs:element name="PC" type="xs:int" />
                                        <xs:element name="PT" type="xs:int" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="club">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="equipo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="enlace" type="xs:string" />
                                        <xs:element name="imagen" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="puntuacion">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="G" type="xs:int" />
                                        <xs:element name="E" type="xs:int" />
                                        <xs:element name="P" type="xs:int" />
                                        <xs:element name="J" type="xs:int" />
                                        <xs:element name="PF" type="xs:int" />
                                        <xs:element name="PC" type="xs:int" />
                                        <xs:element name="PT" type="xs:int" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="club">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="equipo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="enlace" type="xs:string" />
                                        <xs:element name="imagen" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="puntuacion">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="G" type="xs:int" />
                                        <xs:element name="E" type="xs:int" />
                                        <xs:element name="P" type="xs:int" />
                                        <xs:element name="J" type="xs:int" />
                                        <xs:element name="PF" type="xs:int" />
                                        <xs:element name="PC" type="xs:int" />
                                        <xs:element name="PT" type="xs:int" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="club">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="equipo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="enlace" type="xs:string" />
                                        <xs:element name="imagen" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="puntuacion">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="G" type="xs:int" />
                                        <xs:element name="E" type="xs:int" />
                                        <xs:element name="P" type="xs:int" />
                                        <xs:element name="J" type="xs:int" />
                                        <xs:element name="PF" type="xs:int" />
                                        <xs:element name="PC" type="xs:int" />
                                        <xs:element name="PT" type="xs:int" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Sendoaa/Web_DAW_1/xml/XML_temporada2/clasificacion.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="cdcatalog.xsl"?>
<tabla xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../xsd/clasificacion.xsd">
  <tempActual>2</tempActual>
  <club>
    <equipo>
      <nombre>CochinosBC</nombre><enlace>../../html/paginaclub/PagCochinosBC.html</enlace><imagen>../../imagenes/escudos/CochinosBC.png</imagen>
    </equipo>
    <puntuacion>
      <G>2</G><E>1</E><P>0</P><J>3</J><PF>95</PF><PC>86</PC><PT>5</PT>
    </puntuacion>
  </club>
  <club>
    <equipo>
      <nombre>S.Calva</nombre><enlace>../../html/paginaclub/PagS.Calva.html</enlace><imagen>../../imagenes/escudos/S.Calva.png</imagen>
    </equipo>
    <puntuacion>
      <G>2</G><E>1</E><P>0</P><J>3</J><PF>80</PF><PC>49</PC><PT>5</PT>
    </puntuacion>
  </club>
  <club>
    <equipo>
      <nombre>FTaxiBC</nombre><enlace>../../html/paginaclub/PagFTaxiBC.html</enlace><imagen>../../imagenes/escudos/FTaxiBC.png</imagen>
    </equipo>
    <puntuacion>
      <G>2</G><E>0</E><P>1</P><J>3</J><PF>154</PF><PC>131</PC><PT>4</PT>
    </puntuacion>
  </club>
  <club>
    <equipo>
      <nombre>RealTetris</nombre><enlace>../../html/paginaclub/PagRealTetris.html</enlace><imagen>../../imagenes/escudos/RealTetris.png</imagen>
    </equipo>
    <puntuacion>
      <G>2</G><E>0</E><P>1</P><J>3</J><PF>16</PF><PC>27</PC><PT>4</PT>
    </puntuacion>
  </club>
  <club>
    <equipo>
      <nombre>ChimMadrid</nombre><enlace>../../html/paginaclub/PagChimMadrid.html</enlace><imagen>../../imagenes/escudos/ChimMadrid.png</imagen>
    </equipo>
    <puntuacion>
      <G>1</G><E>1</E><P>1</P><J>3</J><PF>166</PF><PC>144</PC><PT>3</PT>
    </puntuacion>
  </club>
  <club>
    <equipo>
      <nombre>Webilbao</nombre><enlace>../../html/paginaclub/PagWebilbao.html</enlace><imagen>../../imagenes/escudos/Webilbao.png</imagen>
    </equipo>
    <puntuacion>
      <G>1</G><E>1</E><P>1</P><J>3</J><PF>74</PF><PC>78</PC><PT>3</PT>
    </puntuacion>
  </club>
  <club>
    <equipo>
      <nombre>KiwisBC</nombre><enlace>../../html/paginaclub/PagKiwisBC.html</enlace><imagen>../../imagenes/escudos/KiwisBC.png</imagen>
    </equipo>
    <puntuacion>
      <G>1</G><E>0</E><P>2</P><J>3</J><PF>100</PF><PC>125</PC><PT>2</PT>
    </puntuacion>
  </club>
  <club>
    <equipo>
      <nombre>PSOEBC</nombre><enlace>../../html/paginaclub/PagPSOEBC.html</enlace><imagen>../../imagenes/escudos/PSOEBC.png</imagen>
    </equipo>
    <puntuacion>
      <G>1</G><E>0</E><P>2</P><J>3</J><PF>94</PF><PC>105</PC><PT>2</PT>
    </puntuacion>
  </club>
  <club>
    <equipo>
      <nombre>Poucelona</nombre><enlace>../../html/paginaclub/PagPoucelona.html</enlace><imagen>../../imagenes/escudos/Poucelona.png</imagen>
    </equipo>
    <puntuacion>
      <G>1</G><E>0</E><P>2</P><J>3</J><PF>24</PF><PC>28</PC><PT>2</PT>
    </puntuacion>
  </club>
  <club>
    <equipo>
      <nombre>At.Mandril</nombre><enlace>../../html/paginaclub/PagAt.Mandril.html</enlace><imagen>../../imagenes/escudos/At.Mandril.png</imagen>
    </equipo>
    <puntuacion>
      <G>0</G><E>0</E><P>3</P><J>3</J><PF>60</PF><PC>90</PC><PT>0</PT>
    </puntuacion>
  </club>
</tabla>
