=== Sendoaa/Web_DAW_1/xml/xsd/clubes.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="clubes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="tempActual" type="xs:int" />
        <xs:element name="equipo">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="escudo">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="enlace" type="xs:anyURI" />
                    <xs:element name="imagen" type="xs:anyURI" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="nombre" type="xs:string" />
              <xs:element name="entrenador" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="equipo">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="escudo">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="enlace" type="xs:anyURI" />
                    <xs:element name="imagen" type="xs:anyURI" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="nombre" type="xs:string" />
              <xs:element name="entrenador" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="equipo">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="escudo">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="enlace" type="xs:anyURI" />
                    <xs:element name="imagen" type="xs:anyURI" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="nombre" type="xs:string" />
              <xs:element name="entrenador" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="equipo">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="escudo">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="enlace" type="xs:anyURI" />
                    <xs:element name="imagen" type="xs:anyURI" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="nombre" type="xs:string" />
              <xs:element name="entrenador" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="equipo">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="escudo">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="enlace" type="xs:anyURI" />
                    <xs:element name="imagen" type="xs:anyURI" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="nombre" type="xs:string" />
              <xs:element name="entrenador" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="equipo">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="escudo">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="enlace" type="xs:anyURI" />
                    <xs:element name="imagen" type="xs:anyURI" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="nombre" type="xs:string" />
              <xs:element name="entrenador" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="equipo">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="escudo">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="enlace" type="xs:anyURI" />
                    <xs:element name="imagen" type="xs:anyURI" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="nombre" type="xs:string" />
              <xs:element name="entrenador" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="equipo">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="escudo">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="enlace" type="xs:anyURI" />
                    <xs:element name="imagen" type="xs:anyURI" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="nombre" type="xs:string" />
              <xs:element name="entrenador" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="equipo">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="escudo">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="enlace" type="xs:anyURI" />
                    <xs:element name="imagen" type="xs:anyURI" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="nombre" type="xs:string" />
              <xs:element name="entrenador" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="equipo">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="escudo">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="enlace" type="xs:anyURI" />
                    <xs:element name="imagen" type="xs:anyURI" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="nombre" type="xs:string" />
              <xs:element name="entrenador" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Sendoaa/Web_DAW_1/xml/XML_temporada1/clubes.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="cdcatalog.xsl"?>
<clubes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../xsd/clubes.xsd">
  <tempActual>1</tempActual>
  <equipo>
    <escudo>
      <enlace>../html/paginaclub/PagKiwisBC.html</enlace>
      <imagen>../imagenes/escudos/KiwisBC.png</imagen>
    </escudo>
    <nombre>KiwisBC</nombre>
    <entrenador>Jose Smith</entrenador>
  </equipo>
  <equipo>
    <escudo>
      <enlace>../html/paginaclub/PagPoucelona.html</enlace>
      <imagen>../imagenes/escudos/Poucelona.png</imagen>
    </escudo>
    <nombre>Poucelona</nombre>
    <entrenador>Congito Moreno</entrenador>
  </equipo>
  <equipo>
    <escudo>
      <enlace>../html/paginaclub/PagChimMadrid.html</enlace>
      <imagen>../imagenes/escudos/ChimMadrid.png</imagen>
    </escudo>
    <nombre>ChimMadrid</nombre>
    <entrenador>Patricio Lunar</entrenador>
  </equipo>
  <equipo>
    <escudo>
      <enlace>../html/paginaclub/PagAt.Mandril.html</enlace>
      <imagen>../imagenes/escudos/At.Mandril.png</imagen>
    </escudo>
    <nombre>At.Mandril</nombre>
    <entrenador>Pedro Maza</entrenador>
  </equipo>
  <equipo>
    <escudo>
      <enlace>../html/paginaclub/PagFTaxiBC.html</enlace>
      <imagen>../imagenes/escudos/FTaxiBC.png</imagen>
    </escudo>
    <nombre>FTaxiBC</nombre>
    <entrenador>Chibolo Mondongo</entrenador>
  </equipo>
  <equipo>
    <escudo>
      <enlace>../html/paginaclub/PagWebilbao.html</enlace>
      <imagen>../imagenes/escudos/Webilbao.png</imagen>
    </escudo>
    <nombre>Webilbao</nombre>
    <entrenador>Oscar Meza</entrenador>
  </equipo>
  <equipo>
    <escudo>
      <enlace>../html/paginaclub/PagS.Calva.html</enlace>
      <imagen>../imagenes/escudos/S.Calva.png</imagen>
    </escudo>
    <nombre>S.Calva</nombre>
    <entrenador>Yael Herrera</entrenador>
  </equipo>
  <equipo>
    <escudo>
      <enlace>../html/paginaclub/PagPSOEBC.html</enlace>
      <imagen>../imagenes/escudos/PSOEBC.png</imagen>
    </escudo>
    <nombre>PSOEBC</nombre>
    <entrenador>Carlos Ruiz</entrenador>
  </equipo>
  <equipo>
    <escudo>
      <enlace>../html/paginaclub/PagRealTetris.html</enlace>
      <imagen>../imagenes/escudos/RealTetris.png</imagen>
    </escudo>
    <nombre>RealTetris</nombre>
    <entrenador>Pep Pipiolo</entrenador>
  </equipo>
  <equipo>
    <escudo>
      <enlace>../html/paginaclub/PagCochinosBC.html</enlace>
      <imagen>../imagenes/escudos/CochinosBC.png</imagen>
    </escudo>
    <nombre>CochinosBC</nombre>
    <entrenador>Nayib Bukele</entrenador>
  </equipo>
</clubes>
